### ISSUE TITLE
Error on example

### ISSUE THREAD

**Issue by LeandroFavero** [Loknar/node-winsay#5]
Hi,

When I execute this example from documents:
winsay.speak("Good News', 'You've won the internet!", function () {
     console.log("text to speech complete");
});

I receive this error:
C:\test2\node_modules\winsay\winsay.js:25
            throw error;
            ^
 Error: Object reference not set to an instance of an object.
    at Error (native)
    at <anonymous>:1:55
    at speakSync (C:\test2\node_modules\winsay\winsay.js:22:5)
    at process.<anonymous> (C:\test2\node_modules\winsay\speakAsync.js:4:5)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:695:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
 This text is printed after you encounter the wild Pikachu.

**Comment by Loknar** [comment]
Hi @LeandroFavero, on what OS are you running into this? Windows 7, 8 or 10?
Did you try upping the required edge dependency to the newest version? It's [5.9.2](https://www.npmjs.com/package/edge) now I think .. I'll take a look when I'm in front of a Windows computer.

**Comment by LeandroFavero** [comment]
10.
Speak in synchronous mode, this error happens only in Async
